/**
 * Mixamo Animation Library Generator
 *
 * Builds animation-library.json + animation-library.csv + LIBRARY_README.md
 *
 * Usage:
 *   node generate-library.mjs [output_dir]
 *   set MIXAMO_TOKEN=<tok> && node generate-library.mjs   → +fps/loop from API
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname    = path.dirname(fileURLToPath(import.meta.url));
const CACHE_FILE   = path.join(__dirname, '..', 'animations-cache.json');

const ANIM_DIR     = process.argv[2] || path.join(__dirname, '..', 'Animations');
const GIF_DIR      = path.join(ANIM_DIR, '_GIF');
const OUT_JSON     = path.join(ANIM_DIR, 'animation-library.json');
const OUT_CSV      = path.join(ANIM_DIR, 'animation-library.csv');
const OUT_README   = path.join(ANIM_DIR, 'LIBRARY_README.md');

const BEARER       = process.env.MIXAMO_TOKEN || '';
const CHARACTER_ID = process.env.MIXAMO_CHARACTER || '721c276f-a08a-406a-bcf0-6a9e3c607770';
const ENRICH_API   = !!BEARER;
const CONCURRENCY  = 6;
const DELAY_MS     = 80;

const SCHEMA = {
  _description: 'Mixamo Animation Library — generated by Mixamo Downloader',
  _note: 'See LIBRARY_README.md in this folder for full documentation.',
  fields: {
    id:                    'Mixamo product UUID (unique identifier)',
    motion_id:             'Mixamo motion UUID (may equal id)',
    source:                'Origin: "mixamo" (extensible for other sources)',
    type:                  '"Motion" (all entries here are single animations)',
    name:                  'Short display name from Mixamo',
    description:           'Full descriptive name — used as the filename base',
    character_type:        'Target rig type, e.g. "human"',
    pack:                  'Pack name if from a pack, null for standalone',
    pack_description:      'All motion names listed in the pack (comma-separated)',
    fbx_file:              'RELATIVE path to .fbx from this file\'s location',
    gif_file:              'RELATIVE path to .gif preview from this file\'s location',
    fbx_downloaded:        'true = file exists on disk',
    gif_downloaded:        'true = GIF preview exists on disk',
    also_in_packs:         '[standalone only] list of pack names this animation also appears in',
    standalone_duplicate:  '[pack only] if identical animation exists standalone: {id, description, fbx_file, gif_file}',
    fps:                   'Frames per second (populated when API-enriched)',
    loop:                  'Whether animation loops (populated when API-enriched)',
    thumbnail:             'CDN URL to static PNG thumbnail',
    thumbnail_animated:    'CDN URL to animated GIF preview',
    updated_at:            'ISO timestamp of last update',
  }
};

function sanitize(name) {
  return name.replace(/[<>:"/\\|?*]+/g, '_').replace(/\s+/g, ' ').trim();
}
function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }
function rel(...parts) { return path.join(...parts).replace(/\\/g, '/'); }
function fileExists(...parts) { try { return fs.existsSync(path.join(...parts)); } catch { return false; } }

function loadCache() {
  if (!fs.existsSync(CACHE_FILE)) { console.error('Missing animations-cache.json!'); process.exit(1); }
  return JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8')).anims;
}

function loadExistingLibrary() {
  try {
    if (!fs.existsSync(OUT_JSON)) return {};
    const data = JSON.parse(fs.readFileSync(OUT_JSON, 'utf8'));
    const list = Array.isArray(data.animations) ? data.animations : Object.values(data.animations || {});
    const obj = {};
    list.forEach(e => { if (e.id) obj[e.id] = e; });
    return obj;
  } catch { return {}; }
}

async function fetchProduct(productId) {
  const url = `https://www.mixamo.com/api/v1/products/${productId}?similar=0&character_id=${CHARACTER_ID}`;
  const res = await fetch(url, {
    headers: { 'Accept': 'application/json', 'Authorization': `Bearer ${BEARER}`, 'X-Api-Key': 'mixamo2' }
  });
  if (!res.ok) throw new Error(`${res.status}`);
  return res.json();
}

async function runConcurrent(tasks, n) {
  let idx = 0;
  async function worker() {
    while (idx < tasks.length) { const i = idx++; await tasks[i](); }
  }
  await Promise.all(Array.from({ length: Math.min(n, tasks.length) }, worker));
}

function getUniquePacks(anims) {
  const seen = new Set();
  return anims.filter(a => {
    if (a.type !== 'MotionPack' || !Array.isArray(a.motions)) return false;
    const key = a.name + '|' + a.motions.length;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function csvEscape(v) {
  if (v == null) return '';
  const s = String(v);
  return (s.includes(',') || s.includes('"') || s.includes('\n'))
    ? '"' + s.replace(/"/g, '""') + '"' : s;
}
function toCsvRow(fields) { return fields.map(csvEscape).join(','); }

// ── README generator ─────────────────────────────────────────────────

function generateReadme(summary, uniquePacks, entries) {
  const animations = Object.values(entries);
  const standalone = animations.filter(e => !e.pack);
  const packAnims  = animations.filter(e => e.pack);
  const dupCount   = packAnims.filter(e => e.standalone_duplicate).length;
  const uniquePack = packAnims.filter(e => !e.standalone_duplicate).length;

  const packList = uniquePacks.map(p => {
    const motions = animations.filter(e => e.pack === p.name);
    const dups    = motions.filter(e => e.standalone_duplicate).length;
    return `| ${p.name.padEnd(38)} | ${String(motions.length).padStart(3)} | ${String(dups).padStart(3)} dup + ${String(motions.length - dups).padStart(3)} unique |`;
  }).sort();

  return `# Mixamo Animation Library

Generated: ${summary.generated_at}
Source: Mixamo (mixamo.com)

---

## Folder Structure

All paths below are relative to this file's location (the animations root folder).

\`\`\`
[this folder]/
│
├── LIBRARY_README.md           ← this file
├── animation-library.json      ← full machine-readable index
├── animation-library.csv       ← spreadsheet-friendly version
│
├── Animations/                 ← ${standalone.length} standalone animations
│   ├── Running.fbx
│   ├── Idle.fbx
│   └── ...
│
├── _Packs/                     ← ${uniquePacks.length} animation packs
│   ├── Action Adventure Pack/
│   │   ├── idle.fbx
│   │   ├── running.fbx
│   │   └── ...
│   └── [other packs]/
│       └── ...
│
└── _GIF/                       ← animated preview GIFs (mirror structure)
    ├── Running.gif
    ├── Idle.gif
    ├── ...
    └── _Packs/
        ├── Action Adventure Pack/
        │   ├── idle.gif
        │   └── ...
        └── [other packs]/
\`\`\`

---

## Statistics

| Category               | Count  |
|------------------------|--------|
| Total animations       | ${String(summary.total_animations).padStart(6)} |
| Standalone (root)      | ${String(summary.standalone).padStart(6)} |
| Pack animations        | ${String(summary.from_packs).padStart(6)} |
| — duplicates of standalone | ${String(dupCount).padStart(3)} |
| — unique to packs only     | ${String(uniquePack).padStart(3)} |
| FBX files on disk      | ${String(summary.fbx_downloaded).padStart(6)} |
| GIF files on disk      | ${String(summary.gif_downloaded).padStart(6)} |

---

## Duplicate Animations Explained

**${dupCount} animations appear BOTH as standalone AND inside a pack.**

Mixamo sells packs as themed bundles — but most of their content is just
a curated selection of animations that also exist individually in the catalog.

Example:
- \`Running.fbx\`  ← standalone animation in root
- \`_Packs/Male Locomotion Pack/running.fbx\`  ← same motion, same product_id

They share the **same Mixamo product_id** — it is literally the same file.

### How duplicates are marked in animation-library.json

**Standalone entry** gets \`also_in_packs\`:
\`\`\`json
{
  "description": "Running",
  "pack": null,
  "also_in_packs": ["Male Locomotion Pack", "Female Locomotion Pack"],
  "fbx_file": "Running.fbx"
}
\`\`\`

**Pack entry** gets \`standalone_duplicate\`:
\`\`\`json
{
  "name": "running",
  "pack": "Male Locomotion Pack",
  "standalone_duplicate": {
    "id": "...",
    "description": "Running",
    "fbx_file": "Running.fbx",
    "gif_file": "_GIF/Running.gif"
  },
  "fbx_file": "_Packs/Male Locomotion Pack/running.fbx"
}
\`\`\`

**${uniquePack} animations are unique to their pack** — they do not exist as standalone.

---

## animation-library.json Fields

| Field                 | Type     | Description |
|-----------------------|----------|-------------|
| \`id\`                  | string   | Mixamo product UUID (primary key) |
| \`motion_id\`           | string   | Mixamo motion UUID |
| \`source\`              | string   | Always \`"mixamo"\` — extensible for future sources |
| \`type\`                | string   | Always \`"Motion"\` for individual animations |
| \`name\`                | string   | Short display name (e.g. \`"Hip Hop Dancing"\`) |
| \`description\`         | string   | Full name used as filename (e.g. \`"Hip Hop Dancing Bboy Variation One"\`) |
| \`character_type\`      | string   | Rig type, e.g. \`"human"\` |
| \`pack\`                | string\\|null | Pack name, or \`null\` for standalone |
| \`pack_description\`    | string\\|null | All motion names in the pack, comma-separated |
| \`fbx_file\`            | string   | **Relative** path to .fbx from this file |
| \`gif_file\`            | string   | **Relative** path to .gif preview from this file |
| \`fbx_downloaded\`      | boolean  | \`true\` if .fbx exists on disk |
| \`gif_downloaded\`      | boolean  | \`true\` if .gif exists on disk |
| \`also_in_packs\`       | string[] | *(standalone only)* pack names that include this animation |
| \`standalone_duplicate\`| object\\|null | *(pack only)* reference to the standalone version if it exists |
| \`fps\`                 | number\\|null | Frames per second (from API enrichment) |
| \`loop\`                | bool\\|null  | Loops? (from API enrichment) |
| \`thumbnail\`           | string   | CDN URL to static PNG preview |
| \`thumbnail_animated\`  | string   | CDN URL to animated GIF preview |
| \`updated_at\`          | string   | ISO 8601 timestamp |

---

## Packs

${packList.join('\n')}

---

## Using This Library

### Load all standalone animations
\`\`\`js
const lib = JSON.parse(fs.readFileSync('animation-library.json'));
const standalone = lib.animations.filter(a => !a.pack && a.fbx_downloaded);
\`\`\`

### Load all animations from a specific pack
\`\`\`js
const pack = lib.animations.filter(a => a.pack === 'Breakdance Pack');
\`\`\`

### Find the GIF for an animation
\`\`\`js
const anim = lib.animations.find(a => a.description === 'Running');
const gifPath = path.join(libraryDir, anim.gif_file);
\`\`\`

### Check if a pack animation has a standalone version
\`\`\`js
const packAnim = lib.animations.find(a => a.pack === 'Male Locomotion Pack' && a.name === 'running');
if (packAnim.standalone_duplicate) {
  console.log('Standalone version:', packAnim.standalone_duplicate.fbx_file);
}
\`\`\`

### Avoid loading duplicate files
\`\`\`js
// Only load animations that are NOT duplicates of standalone versions
const unique = lib.animations.filter(a => !a.pack || !a.standalone_duplicate);
\`\`\`
`;
}

// ── Main ─────────────────────────────────────────────────────────────

async function main() {
  const anims        = loadCache();
  const uniquePacks  = getUniquePacks(anims);
  const regularAnims = anims.filter(a => a.type !== 'MotionPack');

  console.log(`Folder: ${ANIM_DIR}`);
  console.log(`Cache: ${regularAnims.length} regular, ${uniquePacks.length} packs`);

  const existing = loadExistingLibrary();
  const entries  = {};

  // ── Build lookup maps for cross-references ───────────────────────
  // regularById: id → regular animation entry info
  const regularById = {};
  regularAnims.forEach(a => {
    regularById[a.id] = {
      id:          a.id,
      description: a.description,
      fbx_file:    rel('Animations', sanitize(a.description) + '.fbx'),
      gif_file:    rel('_GIF', sanitize(a.description) + '.gif'),
    };
  });

  // packsByProductId: product_id → [pack names]
  const packsByProductId = {};
  uniquePacks.forEach(pack => {
    pack.motions.forEach(m => {
      if (!m.product_id) return;
      if (!packsByProductId[m.product_id]) packsByProductId[m.product_id] = [];
      if (!packsByProductId[m.product_id].includes(pack.name)) {
        packsByProductId[m.product_id].push(pack.name);
      }
    });
  });

  // ── Regular animations ───────────────────────────────────────────
  console.log(`\nRegular animations (${regularAnims.length})...`);
  let done = 0;

  const regTasks = regularAnims.map(anim => async () => {
    const baseName    = sanitize(anim.description);
    const fbxFile     = rel('Animations', baseName + '.fbx');
    const gifFile     = rel('_GIF', baseName + '.gif');
    const prev        = existing[anim.id] || {};
    const alsoInPacks = packsByProductId[anim.id] || [];

    const entry = {
      id:                 anim.id,
      motion_id:          anim.motion_id,
      source:             'mixamo',
      type:               anim.type,
      name:               anim.name,
      description:        anim.description,
      character_type:     anim.character_type,
      pack:               null,
      pack_description:   null,
      fbx_file:           fbxFile,
      gif_file:           gifFile,
      fbx_downloaded:     fileExists(ANIM_DIR, 'Animations', baseName + '.fbx'),
      gif_downloaded:     fileExists(GIF_DIR,  baseName + '.gif'),
      also_in_packs:      alsoInPacks.length > 0 ? alsoInPacks.sort() : undefined,
      thumbnail:          anim.thumbnail          || null,
      thumbnail_animated: anim.thumbnail_animated || null,
      fps:                prev.fps  ?? null,
      loop:               prev.loop ?? null,
      updated_at:         new Date().toISOString(),
    };

    if (ENRICH_API && !prev.fps) {
      try {
        const prod = await fetchProduct(anim.id);
        if (prod.details) { entry.fps = prod.details.fps ?? null; entry.loop = prod.details.loop ?? null; }
        await sleep(DELAY_MS);
      } catch { /* skip */ }
    }

    entries[anim.id] = entry;
    done++;
    if (done % 300 === 0) process.stdout.write(`\r  ${done}/${regularAnims.length}...`);
  });

  await runConcurrent(regTasks, ENRICH_API ? CONCURRENCY : 30);
  console.log(`\r  ${done}/${regularAnims.length} — done`);

  // ── Pack animations ──────────────────────────────────────────────
  console.log(`\nPacks (${uniquePacks.length})...`);
  let packDone = 0;

  for (const pack of uniquePacks) {
    const packLabel  = sanitize(pack.name);
    const packFbxDir = path.join(ANIM_DIR, '_Packs', packLabel);
    const packGifDir = path.join(GIF_DIR,  '_Packs', packLabel);

    for (const motion of pack.motions) {
      const id       = motion.product_id || `${pack.motion_id}_${sanitize(motion.name)}`;
      const baseName = sanitize(motion.name);
      const fbxFile  = rel('_Packs', packLabel, baseName + '.fbx');
      const gifFile  = rel('_GIF', '_Packs', packLabel, baseName + '.gif');
      const prev     = existing[id] || {};

      // Cross-reference: does this motion also exist as a standalone?
      const standaloneRef = (motion.product_id && regularById[motion.product_id])
        ? regularById[motion.product_id]
        : null;

      const entry = {
        id,
        motion_id:             motion.motion_id || null,
        source:                'mixamo',
        type:                  'Motion',
        name:                  motion.name,
        description:           motion.name,
        character_type:        pack.character_type || 'human',
        pack:                  pack.name,
        pack_description:      pack.description   || null,
        fbx_file:              fbxFile,
        gif_file:              gifFile,
        fbx_downloaded:        fileExists(packFbxDir, baseName + '.fbx'),
        gif_downloaded:        fileExists(packGifDir, baseName + '.gif'),
        standalone_duplicate:  standaloneRef,
        thumbnail:             prev.thumbnail          || pack.thumbnail          || null,
        thumbnail_animated:    prev.thumbnail_animated || pack.thumbnail_animated || null,
        fps:                   prev.fps  ?? null,
        loop:                  prev.loop ?? null,
        updated_at:            new Date().toISOString(),
      };

      if (ENRICH_API && motion.product_id && !prev.thumbnail_animated) {
        try {
          const prod = await fetchProduct(motion.product_id);
          entry.thumbnail          = prod.thumbnail          || entry.thumbnail;
          entry.thumbnail_animated = prod.thumbnail_animated || entry.thumbnail_animated;
          if (prod.details) { entry.fps = prod.details.fps ?? null; entry.loop = prod.details.loop ?? null; }
          await sleep(DELAY_MS);
        } catch { /* skip */ }
      }

      entries[id] = entry;
      packDone++;
    }
    process.stdout.write(`\r  ${packDone} pack animations...`);
  }
  console.log(`\r  ${packDone} pack animations — done`);

  // ── Sort ─────────────────────────────────────────────────────────
  const animations = Object.values(entries).sort((a, b) => {
    if (!a.pack && b.pack) return -1;
    if (a.pack && !b.pack) return 1;
    if (a.pack !== b.pack) return (a.pack || '').localeCompare(b.pack || '');
    return (a.description || '').localeCompare(b.description || '');
  });

  const fbxCount    = animations.filter(e => e.fbx_downloaded).length;
  const gifCount    = animations.filter(e => e.gif_downloaded).length;
  const packCount   = animations.filter(e => e.pack).length;
  const packNames   = [...new Set(animations.filter(e => e.pack).map(e => e.pack))];

  const summary = {
    generated_at:     new Date().toISOString(),
    source:           'mixamo',
    library_version:  3,
    total_animations: animations.length,
    standalone:       animations.length - packCount,
    from_packs:       packCount,
    packs_count:      uniquePacks.length,
    pack_names:       packNames.sort(),
    fbx_downloaded:   fbxCount,
    gif_downloaded:   gifCount,
    api_enriched:     ENRICH_API,
  };

  // ── Save JSON ────────────────────────────────────────────────────
  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
  fs.writeFileSync(OUT_JSON, JSON.stringify({ schema: SCHEMA, summary, animations }, null, 2), 'utf8');
  console.log(`\nJSON:   ${OUT_JSON} (${(fs.statSync(OUT_JSON).size / 1024).toFixed(0)} KB)`);

  // ── Save CSV ─────────────────────────────────────────────────────
  const csvHeaders = [
    'name', 'description', 'source', 'type', 'pack', 'pack_description',
    'also_in_packs', 'standalone_duplicate',
    'fbx_file', 'gif_file', 'fbx_downloaded', 'gif_downloaded',
    'fps', 'loop', 'thumbnail_animated', 'id', 'motion_id'
  ];
  const csvRows = [
    toCsvRow(csvHeaders),
    ...animations.map(e => toCsvRow(csvHeaders.map(h => {
      const v = e[h];
      if (Array.isArray(v)) return v.join('; ');
      if (v && typeof v === 'object') return v.fbx_file || JSON.stringify(v);
      return v ?? '';
    })))
  ];
  fs.writeFileSync(OUT_CSV, '\uFEFF' + csvRows.join('\r\n'), 'utf8');
  console.log(`CSV:    ${OUT_CSV} (${(fs.statSync(OUT_CSV).size / 1024).toFixed(0)} KB)`);

  // ── Save README ──────────────────────────────────────────────────
  const readmeContent = generateReadme(summary, uniquePacks, entries);
  fs.writeFileSync(OUT_README, readmeContent, 'utf8');
  console.log(`README: ${OUT_README}`);

  // ── Summary ──────────────────────────────────────────────────────
  const dupCount    = animations.filter(e => e.pack && e.standalone_duplicate).length;
  const uniquePack  = animations.filter(e => e.pack && !e.standalone_duplicate).length;
  console.log('\n── Summary ───────────────────────────────────────────────');
  console.log(`  Total:                  ${summary.total_animations}`);
  console.log(`  Standalone:             ${summary.standalone}`);
  console.log(`  From packs:             ${summary.from_packs}`);
  console.log(`    — standalone duplicates: ${dupCount}`);
  console.log(`    — unique to packs:       ${uniquePack}`);
  console.log(`  FBX on disk:            ${fbxCount}`);
  console.log(`  GIF on disk:            ${gifCount}`);
}

main().catch(err => { console.error('Fatal:', err); process.exit(1); });
